[package]
name = "idna_adapter"
version = "1.3.0"
rust-version = "1.81"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = ["The rust-url developers"]
readme = "README.md"
description = "Back end adapter for idna"
categories = ["no-std", "internationalization"]
keywords = ["unicode", "dns", "idna"]
documentation = "https://docs.rs/idna_adapter/latest/idna_adapter/"
homepage = "https://docs.rs/crate/idna_adapter/latest" # README link
repository = "https://github.com/hsivonen/idna_adapter"

[dependencies]
idn = "1"

[features]
compiled_data = []
